### ISSUE TITLE
client-backend Doesnt Auto Detect TF2 Folder, Even with all Instructions Followed in Both YT and README

### ISSUE THREAD

**Issue by milanjan10** [MegaAntiCheat/client-backend#102]
Hello, I was Doing a First time cargo run on the client-backend folder, but when it finished, I got shown an Error message, stating that it could not autodetect the TF2 Folder, and that i should use Launch Options in order to Specify the Folder's Location.
I tried following instructions of error message, Stating i had to fill in a Launch Option, But Windows Doesnt support "'s In the Right Click Properties Menu, Which the specified launch option had, Therefore Making it useless.
I even tried via Adding as a Non Steam game, It worked, Got everything correct, But opening it results in the code being shown via Notepad, Not actually run via Powershell or Command Prompt. I Even went as far as following Exact step after step From the YouTube Tutorial, From Git Cloning to the Documents folder, To Setting up an autoexec.cfg file in the TF2 Local Files, But to no avail.

I have the log here (This is a first time cargo run, hence the load of compilation messages. Error Message in Question is in Bold and Italic)

   Compiling proc-macro2 v1.0.66
   Compiling serde v1.0.175
   Compiling windows_x86_64_msvc v0.48.0
   Compiling winapi v0.3.9
   Compiling once_cell v1.18.0
   Compiling windows-targets v0.48.1
   Compiling windows-sys v0.48.0
   Compiling memchr v2.5.0
   Compiling quote v1.0.32
   Compiling syn v2.0.27
   Compiling pin-project-lite v0.2.10
   Compiling futures-core v0.3.28
   Compiling log v0.4.19
   Compiling smallvec v1.11.0
   Compiling lock_api v0.4.10
   Compiling parking_lot_core v0.9.8
   Compiling syn v1.0.109
   Compiling serde_derive v1.0.175
   Compiling itoa v1.0.9
   Compiling slab v0.4.8
   Compiling futures-sink v0.3.28
   Compiling scopeguard v1.2.0
   Compiling tokio v1.29.1
   Compiling futures-task v0.3.28
   Compiling futures-channel v0.3.28
   Compiling fnv v1.0.7
   Compiling parking_lot v0.12.1
   Compiling socket2 v0.4.9
   Compiling tokio-macros v2.1.0
   Compiling mio v0.8.8
   Compiling num-traits v0.2.16
   Compiling futures-util v0.3.28
   Compiling num_cpus v1.16.0
   Compiling futures-io v0.3.28
   Compiling futures-macro v0.3.28
   Compiling futures v0.1.31
   Compiling thiserror v1.0.44
   Compiling bytes v1.4.0
   Compiling pin-utils v0.1.0
   Compiling libc v0.2.147
   Compiling thiserror-impl v1.0.44
   Compiling tracing-core v0.1.31
   Compiling rustversion v1.0.14
   Compiling tracing-attributes v0.1.26
   Compiling http v0.2.9
   Compiling tracing v0.1.37
   Compiling num-integer v0.1.45
   Compiling indexmap v1.9.3
   Compiling version_check v0.9.4
   Compiling strsim v0.10.0
   Compiling tower-service v0.3.2
   Compiling http-body v0.4.5
   Compiling aho-corasick v1.0.2
   Compiling protobuf v2.28.0
   Compiling httparse v1.8.0
   Compiling ryu v1.0.15
   Compiling hashbrown v0.12.3
   Compiling ucd-trie v0.1.6
   Compiling regex-syntax v0.7.4
   Compiling pest v2.7.1
   Compiling tokio-util v0.7.8
   Compiling regex-automata v0.3.3
   Compiling winapi-util v0.1.5
   Compiling num-bigint v0.3.3
   Compiling native-tls v0.2.11
   Compiling cc v1.0.79
   Compiling lazy_static v1.4.0
   Compiling ident_case v1.0.1
   Compiling tinyvec_macros v0.1.1
   Compiling either v1.9.0
   Compiling try-lock v0.2.4
   Compiling percent-encoding v2.3.0
   Compiling serde_json v1.0.103
   Compiling form_urlencoded v1.2.0
   Compiling want v0.3.1
   Compiling which v4.4.0
   Compiling tinyvec v1.6.0
   Compiling backtrace v0.3.68
   Compiling regex v1.9.1
   Compiling darling_core v0.13.4
   Compiling same-file v1.0.6
   Compiling h2 v0.3.20
   Compiling pest_meta v2.7.1
   Compiling proc-macro-error-attr v1.0.4
   Compiling schannel v0.1.22
   Compiling num-rational v0.3.2
   Compiling num-iter v0.1.43
   Compiling async-trait v0.1.72
   Compiling adler v1.0.2
   Compiling httpdate v1.0.2
   Compiling fastrand v2.0.0
   Compiling gimli v0.27.3
   Compiling paste v1.0.14
   Compiling protobuf-codegen v2.28.0
   Compiling hyper v0.14.27
   Compiling addr2line v0.20.0
   Compiling tempfile v3.7.0
   Compiling miniz_oxide v0.7.1
   Compiling pest_generator v2.7.1
   Compiling darling_macro v0.13.4
   Compiling walkdir v2.3.3
   Compiling unicode-normalization v0.1.22
   Compiling protoc v2.28.0
   Compiling proc-macro-error v1.0.4
   Compiling object v0.31.1
   Compiling crossbeam-utils v0.8.16
   Compiling unicode-bidi v0.3.13
   Compiling anstyle v1.0.1
   Compiling tower-layer v0.3.2
   Compiling regex-syntax v0.6.29
   Compiling mime v0.3.17
   Compiling winreg v0.10.1
   Compiling anyhow v1.0.72
   Compiling rustc-demangle v0.1.23
   Compiling utf8parse v0.2.1
   Compiling anstyle-parse v0.2.1
   Compiling regex-automata v0.1.10
   Compiling anstyle-wincon v1.0.1
   Compiling idna v0.4.0
   Compiling protoc-rust v2.28.0
   Compiling darling v0.13.4
   Compiling pest_derive v2.7.1
   Compiling tokio-native-tls v0.3.1
   Compiling serde_urlencoded v0.7.1
   Compiling futures-executor v0.3.28
   Compiling err-derive v0.3.1
   Compiling axum-core v0.3.4
   Compiling num-complex v0.3.1
   Compiling num-traits v0.1.43
   Compiling pin-project-internal v1.1.2
   Compiling is-terminal v0.4.9
   Compiling anstyle-query v1.0.0
   Compiling unicode-xid v0.2.4
   Compiling bitflags v1.3.2
   Compiling glob v0.3.1
   Compiling overload v0.1.1
   Compiling colorchoice v1.0.0
   Compiling iovec v0.1.4
   Compiling byteorder v1.4.3
   Compiling steam-protobuf v0.1.2 (https://github.com/MegaAntiCheat/SteamHelper-rs#3b1e462b)
   Compiling bytes v0.4.12
   Compiling anstream v0.3.2
   Compiling nu-ansi-term v0.46.0
   Compiling pin-project v1.1.2
   Compiling synstructure v0.12.6
   Compiling enum_primitive v0.1.1
   Compiling num v0.3.1
   Compiling futures v0.3.28
   Compiling keyvalues-parser v0.1.0
   Compiling hyper-tls v0.5.0
   Compiling serde_with_macros v1.5.2
   Compiling url v2.4.0
   Compiling matchers v0.1.0
   Compiling tracing-log v0.1.3
   Compiling sharded-slab v0.1.4
   Compiling axum v0.6.19
   Compiling bincode v1.3.3
   Compiling steam-language-gen-derive v0.1.2 (https://github.com/MegaAntiCheat/SteamHelper-rs#3b1e462b)
   Compiling num-derive v0.3.3
   Compiling derive-new v0.5.9
   Compiling enum_dispatch v0.3.12
   Compiling serde_repr v0.1.15
   Compiling thread_local v1.1.7
   Compiling encoding_rs v0.8.32
   Compiling substring v1.4.5
   Compiling nom v1.2.4
   Compiling base64 v0.21.2
   Compiling heck v0.4.1
   Compiling arrayref v0.3.7
   Compiling clap_lex v0.5.0
   Compiling time-core v0.1.1
   Compiling equivalent v1.0.1
   Compiling ipnet v2.8.0
   Compiling hashbrown v0.14.0
   Compiling clap_derive v4.3.12
   Compiling indexmap v2.0.0
   Compiling reqwest v0.11.18
   Compiling time v0.3.23
   Compiling clap_builder v4.3.19
   Compiling steam-language-gen v0.1.2 (https://github.com/MegaAntiCheat/SteamHelper-rs#3b1e462b)
   Compiling steamy-vdf v0.2.0
   Compiling tracing-subscriber v0.3.17
   Compiling serde_bser v0.3.1
   Compiling serde_with v1.14.0
   Compiling crossbeam-channel v0.5.8
   Compiling keyvalues-serde v0.1.0
   Compiling steamid-ng v1.0.0
   Compiling tower v0.4.13
   Compiling tokio-util v0.6.10
   Compiling serde_path_to_error v0.1.14
   Compiling tappet-derive v0.3.2 (https://github.com/MegaAntiCheat/SteamHelper-rs#3b1e462b)
   Compiling winreg v0.11.0
   Compiling dirs-sys-next v0.1.2
   Compiling filetime v0.2.22
   Compiling include_dir_macros v0.7.3
   Compiling matchit v0.7.0
   Compiling unsafe-libyaml v0.2.9
   Compiling maplit v1.0.2
   Compiling sync_wrapper v0.1.2
   Compiling bitflags v2.3.3
   Compiling http-range-header v0.3.1
   Compiling tower-http v0.4.3
   Compiling include_dir v0.7.3
   Compiling serde_yaml v0.9.25
   Compiling watchman_client v0.8.0
   Compiling directories-next v2.0.0
   Compiling notify v6.1.1
   Compiling tappet v0.5.0 (https://github.com/MegaAntiCheat/SteamHelper-rs#3b1e462b)
   Compiling steamlocate v1.2.1
   Compiling rcon v0.5.2 (https://github.com/MegaAntiCheat/rust-rcon#aef1cb15)
   Compiling tracing-appender v0.2.2
   Compiling clap v4.3.19
   Compiling tokio-stream v0.1.14
   Compiling open v5.0.0
   Compiling client-backend v0.1.0 (C:\Users\omari\Documents\client-backend)
    Finished dev [unoptimized + debuginfo] target(s) in 14m 28s
warning: the following packages contain code that will be rejected by a future version of Rust: nom v1.2.4
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 1`
     Running `target\debug\client_backend.exe`
2024-01-10T18:36:51.055219Z  INFO client_backend::settings: Identified current steam user as 76561199011271334
**_2024-01-10T18:36:51.069568Z ERROR client_backend::settings: Could not locate TF2 directory: Failed to locate TF2 installation.
2024-01-10T18:36:51.069898Z ERROR client_backend::settings: If you have a valid TF2 installation you can specify it manually by appending ' --tf2_dir "Path to Team Fortress 2 folder"' when running the program._**
2024-01-10T18:36:51.186117Z  INFO client_backend: All required launch arguments are present!
2024-01-10T18:36:51.235974Z  INFO client_backend::web: Starting web interface at [insert ip here]
2024-01-10T18:36:51.235621Z ERROR client_backend::io::filewatcher: Failed to open file "tf/console.log": Het systeem kan het opgegeven pad niet vinden. (os error 3)
2024-01-10T18:36:53.745093Z ERROR client_backend::io::command_manager: Rcon connection timeout: deadline has elapsed

**Comment by Bash-09** [comment]
Instead of typing `cargo run`, you will have to specify your TF2 directory by typing `cargo run -- --tf2-dir "Path to Team Fortress 2 folder"`

**Comment by milanjan10** [comment]
Ah, I thought it was supposed to be done via Explorer and setting in properties or Via steam, Not via Powershell/Command Prompt. Thanks
