### ISSUE TITLE
BUG: MAC Alpha not installable on steam deck

### ISSUE THREAD

**Issue by Mistyttm** [MegaAntiCheat/client-backend#112]
The alpha build requires `pkg-config` which should be installed through the system's package manager. However on steamdeck the OS is read only and as such requires unlocking the OS to even get the package installed.

(issue found here in Discord: [Discord link](https://discord.com/channels/1112665618869661726/1199966083449356298)

Seems like the Alpha build just isn't possible to install on steamdeck at this point in time.

**Comment by lili7h** [comment]
None of the devs have a steam deck, and no one on the dev team currently has expressed interest in widening the supported platforms to include steam deck. Thats not to say it never will be supported, but it is saying that we have purposely not considered it, and are actively hindered from developing for it by not having any sort of dev kit for it.

**Comment by jkibort928** [comment]
It could be possible to install SteamOS on a separate drive, maybe even a Virtural Machine. If not, it's always possible to see if a 100% userspace install is possible on a basic Arch system (aka, only touching the home directory) (Although I suppose without SteamOS specifically it would be hard to tell what dependencies you would be missing)

**Comment by Mistyttm** [comment]
> It could be possible to install SteamOS on a separate drive, maybe even a Virtural Machine. If not, it's always possible to see if a 100% userspace install is possible on a basic Arch system (aka, only touching the home directory) (Although I suppose without SteamOS specifically it would be hard to tell what dependencies you would be missing)

I run MAC on base Arch and it runs flawlessly, it's literally just an issue with steamos missing a specific package, which as lillith said is out of scope anyway

**Comment by lili7h** [comment]
if it is down to a specific package missing in that OS due to being locked down, then there is nothing we could likely do anyway, as its likely a dependency of the Rust compiler/runtime itself

**Comment by Bash-09** [comment]
My understanding isn't that the OS is locked down, but that installing extra packages needs to be explicitly enabled. Not sure if that's correct.

**Comment by TacoDelPaco** [comment]
I have MAC running flawlessly on my Steam Deck, you just need to run
`sudo steamos-readonly disable`

**Comment by Bash-09** [comment]
> I have MAC running flawlessly on my Steam Deck, you just need to run `sudo steamos-readonly disable`

Gonna close this as resolved then.

**Comment by alex-ac** [comment]
Note: pkg-config is only needed to build MAC. It is not needed to run it. So building MAC on normal ubuntu machine and copying over the executable file should work.
