### ISSUE TITLE
Launch options not recognized when using paths with %command%

### ISSUE THREAD

**Issue by Ar4m1s** [MegaAntiCheat/client-backend#113]
The launch option string "LD_PRELOAD=$LD_PRELOAD:/usr/lib32/libtcmalloc_minimal.so %command% -condebug -conclearlog -usercon -g15 -novid -nojoy" does not match because the regex does not include the characters `/` `$` `:` `=` `.` even though the string contains the necessary launch options. It is probably a simple fix. I made it work, while not properly tested that just prepending "/$:=\." to the regex fixes the issue. 
```rust
let launch_options_regex =
            Regex::new(r#"\t{6}"LaunchOptions"\t{2}"([(/$:=\.\-\w\%\!\@\^\&)\s]*)""#)
                .expect("Constructing LaunchOptions regex");
```

**Comment by Ar4m1s** [comment]
Alternatively simplify like this: ```rust
let regex = Regex::new(r#"\t{6}"LaunchOptions"\t{2}"([^"]*)""#).unwrap();
```

**Comment by Bash-09** [comment]
Done in #115
