### ISSUE TITLE
"There is no UI bundled with this version of the application."

### ISSUE THREAD

**Issue by TacoDelPaco** [MegaAntiCheat/client-backend#145]
According to the [announcement](https://discord.com/channels/1112665618869661726/1113994656229896212/1234328912763551855) post, this is a known recent issue and I did try redownloading a fresh copy but still no luck.

I reverted the Git repo of `client-backend` to `c9a79599a03a909ceae841e91204ea421581175f` to get things working again.

If you need any more info let me know, or if this is already being fixed 🫠 oof

Thanks

**Comment by Bash-09** [comment]
If you downloaded from the release this shouldn't be an issue, if you downloaded from the pipeline, the UI is not included, if you built the application yourself you'll need to run the appropriate include_ui script before building.

So unless you downloaded this from the most recent release (after Mega updated it), then this is expected.

**Comment by TacoDelPaco** [comment]
I've been updating via git pull's and always running the include_ui.sh script before starting my game, I haven't tried from the release file in awhile and it indeed works as intended.

Thanks for your help 🫠

**Comment by Bash-09** [comment]
> I've been updating via git pull's and always running the include_ui.sh script before starting my game

If you did this and it said there was no UI bundled there was likely something that failed when running the script such as not having npm or pnpm or something else. Glad it's sorted though :)
