### ISSUE TITLE
[Enhancement] A windows icon for client_backend.exe

### ISSUE THREAD

**Issue by MaxOhNoo** [MegaAntiCheat/client-backend#154]
![wojack mega anticheat](https://github.com/MegaAntiCheat/client-backend/assets/87615947/4eda1cf8-316b-49a1-a295-0215736c6345)

I gave client_backend.exe a windows icon. It's got all the default icon resolutions that windows needs (256x256, 48x48, etc.). I implemented the .ico file into the exe through the Resource Hacker decompiler [https://www.angusj.com/resourcehacker/](url)

![image](https://github.com/MegaAntiCheat/client-backend/assets/87615947/17d9a9a4-c33e-473f-ae42-e7121f2fa3ab)

Here's the .ico file and the modified client_backend.exe, because GitHub won't let me upload them directly.

[icon.zip](https://github.com/user-attachments/files/15749927/icon.zip)

**Comment by Bash-09** [comment]
We will not be publishing executable files from anybody other than the main developers on this repository.

If we add an icon on Windows it would be preferable for it to be performed as part of a build step, e.g. like is outlined in [this stackoverflow post](https://stackoverflow.com/questions/30291757/attaching-an-icon-resource-to-a-rust-application) which I'll summarise below:

Include the `winresource` crate and add the following to `build.rs`:
```rust
use std::{env, io};
use winresource::WindowsResource;

fn main() -> io::Result<()> {
    if env::var_os("CARGO_CFG_WINDOWS").is_some() {
        WindowsResource::new()
            // This path can be absolute, or relative to your crate root.
            .set_icon("assets/icon.ico")
            .compile()?;
    }
    Ok(())
}
```

**Comment by Bash-09** [comment]
Also I think it would be cool if the icon was transparent instead of having the white background.

**Comment by MaxOhNoo** [comment]
I'll make a pull request soon, using embed-resource cause winresource doesn't work.
How's the icon?
![megascatterbomb](https://github.com/MegaAntiCheat/client-backend/assets/87615947/bc1bf649-ba11-4f52-81b3-e57ce28ec741)

**Comment by MaxOhNoo** [comment]
Moved to https://github.com/MegaAntiCheat/client-backend/pull/155
Feel free to close this issue
