### ISSUE TITLE
TODO: Overriden settings from command line args will overwrite persistent settings when written out.

### ISSUE THREAD

**Issue by Bash-09** [MegaAntiCheat/client-backend#16]
The command line args are checked for certain settings to override (e.g. port) and applies those changes to the settings struct, meaning any of those override will be written out to the config file when saved.

TODO:
* Add optional field to settings struct for settings that can be overriden (mark field with `#[serde(skip)]`
* Update getter for those settings to return the overriden setting if it exists
* Make command line args set the override setting instead of the main setting.

**Comment by Bash-09** [comment]
Should probably also try write the settings back immediately when they are created so that the config folders and file are created when initially running the application.

**Comment by lili7h** [comment]
Potential solution in #18

**Comment by Bash-09** [comment]
Solved by #18
