### ISSUE TITLE
TODO: Try to locate new TF2 directory if the provided directory is invalid

### ISSUE THREAD

**Issue by Bash-09** [MegaAntiCheat/client-backend#17]
The user could move their TF2 install location without updating their settings, which would cause the stored TF2 directory to be wrong even though it could probably be automatically located.

TODO:
* When loading settings from file, check it's valid with `gamefinder::verify_tf_location`, if not valid then try `locate_tf2_folder`, and if that fails just go back to the original location loaded from settings.

**Comment by THE-EXP** [comment]
Another possibility is to prompt the user about their install location if the stored one fails to be found

**Comment by Bash-09** [comment]
Will be resolved by https://github.com/MegaAntiCheat/client-backend/pull/47

**Comment by Bash-09** [comment]
https://github.com/MegaAntiCheat/client-backend/pull/47 Merged
