### ISSUE TITLE
Increase the visibility of the TOS

### ISSUE THREAD

**Issue by jackmio32** [MegaAntiCheat/client-backend#177]
Currently, as far as I can tell, the TOS/Privacy Policy for the demo streaming component does not seem to be listed anywhere externally (outside of the program itself), when ideally it should be listed somewhere on here and/or on megascatterbomb's website.

**Comment by jayceslesar** [comment]
why? Maybe once the software is downloadable from the website but that isnt the case

**Comment by jackmio32** [comment]
I think its a decent idea so its easier to reference back to when needed, but since this issue has went stale, I'll just close it.
