### ISSUE TITLE
Players not showing up in players tab

### ISSUE THREAD

**Issue by AceLombic** [MegaAntiCheat/client-backend#181]
I pretty much did everything that was in the tutorial but it still just wouldn't work for some reason. My keys and passwords are fine I think but it still wouldn't show the players whenever I join a lobby. I also had the executable running, and typed the launch commands in properties but nothing worked.
![Screenshot 2024-08-10 154717](https://github.com/user-attachments/assets/7b1f8ce0-1745-4e78-b241-fc64c86c2ae0)
![Screenshot 2024-08-10 154733](https://github.com/user-attachments/assets/4f9efc78-e6fd-427f-8348-420ff90f3b72)

**Comment by Bash-09** [comment]
https://github.com/MegaAntiCheat/client-backend?tab=readme-ov-file#troubleshooting
