### ISSUE TITLE
os error 2

### ISSUE THREAD

**Issue by anartoast** [MegaAntiCheat/client-backend#185]
[0m←[2m:←[0m Failed reading bytes from demo "D:\\SteamLibrary\\steamapps\\common\\Team Fortress 2\\tf\\demos\\2024-08-12_22-22-46.dem": O sistema não pode encontrar o arquivo especificado. (os error 2)

how do i fix that? i'm too dumb to understand what it even means. the console spams it after every match

**Comment by Bash-09** [comment]
If you have the option to automatically delete demo files set (in TF2 advanced options, next to the auto record demos setting I think?) then the demo file is deleted at the end of the match before Mac is able to finish uploading the last bits.

It's not a huge issue, but if you want it to stop you'll have to disable that setting (and probably clear out your demos folder manually every now and then to stop them building up).

**Comment by anartoast** [comment]
oh yeah i do, thank you. there is any way to only let it delete when mac uses it fully? if not, maybe it's a todo thing
