### ISSUE TITLE
DEMO: Failed to upload late bytes to masterbase: Server returned 422

### ISSUE THREAD

**Issue by resonant-jovian** [MegaAntiCheat/client-backend#187]
Hi,
This might be a setup error on my end but here goes:
Having agreed to the TOS and with a Masterbase key set and demos for all games auto recorded this is the console output from a one game normal casual session:
`2024-08-13T06:59:37.326044Z  INFO client_backend::command_manager: Succesfully reconnected to RCon`

`2024-08-13T07:02:30.461868Z  INFO client_backend::demo: Opened new demo session with Masterbase: DemoSession(**SESSION TOKEN**)`

`2024-08-13T07:25:58.287468Z ERROR client_backend::demo: Failed to upload late bytes to masterbase: Server returned 422`

`2024-08-13T07:25:59.506411Z  INFO client_backend::masterbase: Closed session **SESSION TOKEN**.`

`2024-08-13T07:26:46.280813Z ERROR client_backend::command_manager: RCon error Connection refused (os error 111)`

My best guess is that something went wrong when retrieving the masterbase key and since everything else works as it should i would like some help with this.

**Comment by resonant-jovian** [comment]
(this has happened several times)

**Comment by ktozhee** [comment]
also having this issue

**Comment by jayceslesar** [comment]
closing as the issue lies in a different codebase https://github.com/MegaAntiCheat/masterbase/issues/86
