### ISSUE TITLE
Failed to lookup steam profiles: Tappet(SteamHttpError("403")) error

### ISSUE THREAD

**Issue by ktozhee** [MegaAntiCheat/client-backend#188]
![image](https://github.com/user-attachments/assets/a6447a66-9b54-45e9-a92b-035c9af6837f)
![image](https://github.com/user-attachments/assets/3a5aee00-9074-42b8-8594-3c9e0832d57d)

**Comment by StealthSteeler** [comment]
I get the same errors when I set the Steam API key to be invalid, so check your Steam API Key

**Comment by ktozhee** [comment]
thanks, my problem was solved
