### ISSUE TITLE
TODO: infer current steam user in client start up

### ISSUE THREAD

**Issue by lili7h** [MegaAntiCheat/client-backend#19]
We need to infer the current steam user during the client start up. Theres a couple ways that this could be done, and having done no/very little research on it myself, these all need to be researched:
- Find some way to infer current steam user from the currently running steam process
- Find some way to infer current user/player from tf2 via RCON
- find some way to infer the current steam user from the provided steam web api key?

The easiest and most manual approach is to just require the current user to provide their steamID64 to the client in the config, but this removes any form of validation so this may not be correct. If we can find an automated approach this would be much much better. We can still implement CLA overrides, but we should avoid just speccing steamID64 for the client user in the configs.

**Comment by Conni243** [comment]
There is a kind of log file  in \Steam\config\loginusers.vdf which tracks the current logged in user. The file includes the Steam ID 64 which i think is what we're looking for.

**Comment by Conni243** [comment]
actually it seems to be an exact copy of libraryfolders.vdf

**Comment by lili7h** [comment]
Yeah you're right!

> Steam/config/loginusers.vdf

```
➜  config cat loginusers.vdf
"users"
{
        "76561198071482715"
        {
                "AccountName"           "nope not getting this"
                "PersonaName"           "Lilith"
                "RememberPassword"              "0"
                "WantsOfflineMode"              "0"
                "SkipOfflineModeWarning"                "0"
                "AllowAutoLogin"                "1"
                "MostRecent"            "1"
                "Timestamp"             "_"
        }
}

**Comment by Conni243** [comment]
also appears to update properly if you switch accounts, tested with my alt

**Comment by Conni243** [comment]
I think thats the Steam cloud backup file, it seems to override the config.cfg file in the tf/cfg folder only when steam cloud sync is enabled

**Comment by Bash-09** [comment]
Done in #18
