### ISSUE TITLE
Failed to upload late bytes to masterbase: Server returned 422

### ISSUE THREAD

**Issue by FenekkuKitsune** [MegaAntiCheat/client-backend#190]
Only just downloaded this today to contribute as I felt a desire to play tf2 again, but I'm getting the title'd error in the terminal every time a demo is started after the first.

**Comment by StealthSteeler** [comment]
That issue is being worked on but it shouldn't impact your ability to upload demos! So continue to use it as you would normally

**Comment by jayceslesar** [comment]
Duplicate of #187
