### ISSUE TITLE
RCon error No connection could be made because the target machine actively refused it. (os error 10061)

### ISSUE THREAD

**Issue by uberchemist** [MegaAntiCheat/client-backend#192]
![image](https://github.com/user-attachments/assets/8c9f88e9-e585-477d-9806-7346ca31bf25)

Opening a separate issue for this RCon error, though not sure if it's related to the "Server returned 422" error.

**Comment by Bash-09** [comment]
https://github.com/MegaAntiCheat/client-backend?tab=readme-ov-file#troubleshooting

**Comment by uberchemist** [comment]
Thanks for the link, I can never navigate Github very well. I fixed the error by changing the port!
