### ISSUE TITLE
Just change the default port already its not funny its just pornography and its been that way for over a year

### ISSUE THREAD

**Issue by ToasterWafflez** [MegaAntiCheat/client-backend#198]
Its just a reference to a furry porn site change it already there are thousands of ports to use by default. 

Enjoy having to read this issue while pushing/pulling changes to the git repo Mega. :D

**Comment by nijahplays** [comment]
+1

**Comment by megascatterbomb** [comment]
I'll take suggestions for alternate port numbers.

Suggest consulting this to avoid conflicts (there's enough problems with TF2 and Apple software both using 27015): https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers

**Comment by nijahplays** [comment]
1984 moment

**Comment by ToasterWafflez** [comment]
1984

**Comment by nijahplays** [comment]
![Cat Me IRL](https://github.com/user-attachments/assets/9ea51623-5aa2-4bb4-a00d-293788e693f9)

**Comment by kiwitf2** [comment]
literally 1984

**Comment by megascatterbomb** [comment]
So there's a slight problem...

Everyone's configs have been generated already and have 3621 set as the webui_port.

These are the choices:
1: Hardcode the port to something else and don't let users configure it.
2: Find a way to override the port set in everyone's configs *without* removing the user's ability to change it.
3: Change the default without affecting the port used by existing users.
4: Simply do not care about the current choice of port.

**Comment by nijahplays** [comment]
> So there's a slight problem...
> 
> Everyone's configs have been generated already and have 3621 set as the webui_port.
> 
> These are the choices: 1: Hardcode the port to something else and don't let users configure it. 2: Find a way to override the port set in everyone's configs _without_ removing the user's ability to change it. 3: Change the default without affecting the port used by existing users. 4: Simply do not care about the current choice of port.

2 or 3 seems fine. I'd prefer 2 but if 3 is easier then do that.

**Comment by megascatterbomb** [comment]
Went with a mix of option 1 and 2 as it turns out the port is already hardcoded in the UI. That can be fixed in a future PR for the UI; the client-backend shouldn't require any further changes than what's in the mentioned PR to accommodate that when it's fixed.

Made an issue for the UI hardcode: https://github.com/MegaAntiCheat/MegaAntiCheat-UI/issues/130
