### ISSUE TITLE
TODO: Batch SteamAPI requests

### ISSUE THREAD

**Issue by Bash-09** [MegaAntiCheat/client-backend#27]
- In SteamAPI loop, accumulate incoming requests into a buffer instead of handling it immediately
- After some time has elapsed (a second, a couple seconds?), then handle those requests.
- Adjust `request_steam_info`, `request_player_summary` and `request_account_bans` to handle a list of players instead of a single one

**Comment by lili7h** [comment]
+ read current steams users friends list from `Steam/userdata/<id3>/config/localconfig.vdf`
