### ISSUE TITLE
Multiple logged in steam accounts cause issue with recognizing launch options

### ISSUE THREAD

**Issue by cgcha** [MegaAntiCheat/client-backend#39]
User was attempting to run MAC backend and the program would not recognize the launch options. Not sure how the steam account is chosen, but it was picking a different one. User solved it by putting launch options in that steam account's tf2 launch options. 

Might need to specify default user id in config.yaml, or some other solution to select which user to use.

**Comment by megascatterbomb** [comment]
I use multiple accounts and haven't run into this issue. The account I use MAC on is the first account that I ever signed into steam on, which may have caused the fault not to occur on my end by chance.

**Comment by lili7h** [comment]
We determine current user by reading `loginusers.vdf`, but I assume this file has multiple entries if there is two accounts saved as logged in on that steam install. I don't have this set up so I can't cross check what that `loginusers.vdf` file would look like, but if it does have multiple entries, we could probably just parse for the most recently logged in account

**Comment by Bash-09** [comment]
Should be resolved by #40
