### ISSUE TITLE
TODO: POST user API endpoint

### ISSUE THREAD

**Issue by Bash-09** [MegaAntiCheat/client-backend#48]
[Spec](https://github.com/MegaAntiCheat/client-backend/wiki/API-Specification#user-post)

TODO:
- Lookup the provided steamids through the Steam API
- Check if there are any saved player  records and attach that data too
- Eventually lookup these players on the Masterbase too, but that won't be available until we actually have a masterbase

**Comment by StevenAlexanderJohnson** [comment]
I'm a bit confused about this project. This repo is supposed to be running on the machine that monitors TF2, why does it have an Axum API?

**Comment by Bash-09** [comment]
> I'm a bit confused about this project. This repo is supposed to be running on the machine that monitors TF2, why does it have an Axum API?

Hi @StevenAlexanderJohnson , yes you are correct that it's the application that monitors the players on the server while playing TF2.

The purpose of the web API is how we decided to separate the application logic from the UI, so that the frontend can be created with anything that can make web requests. The intended use-case is that the frontend is a web-app which can be bundled with the client and run in a browser, which means it can be viewed from inside the steam overlay if a user doesn't have an alternative monitor or doesn't want to minimise the game to interact with it.

See https://github.com/MegaAntiCheat/MegaAntiCheat-UI for the current actual UI. You can compile the UI into the binary with the `include_ui` scripts in the repo, or add your own UI by placing the necessary `index.html` and any other files needed into the `ui` folder before building. They will be automatically hosted at `localhost:3621` when you run the client.

**Comment by StevenAlexanderJohnson** [comment]
I see, I did notice that you also had PR out for Tauri support. Is that going to be pushed through because I think that would be a more intuitive way of handling it. You could create a thread that handles TF2 monitoring separate from the Tauri main thread, and it can be minimized to the tray without being closed.

**Comment by Bash-09** [comment]
Yes, I think Tauri works very well to effectively have a desktop app and I would like to merge it in at some point, it just has some minor issues currently.

**Comment by StevenAlexanderJohnson** [comment]
I was going to look to contribute to this issue, has it already been resolved?
In steamapi.rs it seems that request_steam_info already request user information through the Steam API.

**Comment by StevenAlexanderJohnson** [comment]
do you have a shape for the request body that you would like?
I'm assuming this is a "that person looks sus I'll look them up" rather than an automatic vote kind of thing.

if it's multiple players I could see 
{
    "players": ["id1", "id2", ect...]
 }
 
 else maybe just 
 {
    "player_id": "id"
}

**Comment by Bash-09** [comment]
Yes, we have an initial draft of what the exchange would look like here: https://github.com/MegaAntiCheat/client-backend/wiki/API-Specification#user-post

This isn't set in stone, so feel free to suggest some adjustments. The player objects returned in the json resemble the `Player` struct, although if they aren't in the current server the `GameInfo` field may need to just be set to 0s or possibly omitted entirely.

**Comment by Bash-09** [comment]
Was done in #133
