### ISSUE TITLE
TODO: Functionality for importing TF2BD lists

### ISSUE THREAD

**Issue by Bash-09** [MegaAntiCheat/client-backend#50]
TODO:
- Create a function to parse a TF2BD list into `Vec<Player>` or some other convenient structure.
    - Define some struct the represents the TF2BD representation and derive `serde::Deserialize`
    - Implement conversion to `Vec<PlayerRecord>`
- Command line arg to covert to a standalone list or import into the existing playerlist.
- *API endpoint to import a list? Would need to come up with spec.

**Comment by Bash-09** [comment]
Should be pretty straightforward by defining a struct that represents the TF2BD representation and deriving `Deserialize` from `serde` on it. Then implementing `From<TF2BDRecord>` (or whatever the struct gets called) on `PlayerRecord` will make it trivial to convert between. Added benefit of using `serde` is it would be simple to add reverse functionality to export to a TF2BD list.

**Comment by Bash-09** [comment]
I forgot about how some lists don't have the players but just have an update link to another list which *does* have the players. Handling that case may add slight complexity but I don't imagine it would be very difficult.

**Comment by cgcha** [comment]
How do we want `PlayerRecord` to handle tags? For users marked as cheaters, we can just update the verdict, but the other relevant attributes would probably fit best as tags. I'm not certain if putting them into the `custom_data` part would be best, as it we would have to parse it anyways and then keep a redundant copy in the `Player` object. 
![image](https://github.com/MegaAntiCheat/client-backend/assets/20671184/e0a0ed8f-8e38-4ada-9ada-815eed1fbf1d)

**Comment by Bash-09** [comment]
See https://github.com/MegaAntiCheat/client-backend/pull/63#issuecomment-2161911695
