### ISSUE TITLE
TODO: Implement Steam friends api

### ISSUE THREAD

**Issue by cgcha** [MegaAntiCheat/client-backend#53]
From lilith: `read current steams users friends list from Steam/userdata/<id3>/config/localconfig.vdf`

Or make an API request for the user somewhere near the start.

**Comment by cgcha** [comment]
I also assumed we would want to get the friends list of people ingame so the user could infer if specific groups were in parties, but this also goes into potentially excessive steamapi requests.

**Comment by Bash-09** [comment]
> I also assumed we would want to get the friends list of people ingame so the user could infer if specific groups were in parties

That was my intention initially, however so far there isn't really a good way to use this information yet so friend list steam API requests were turned off for the moment to avoid spamming useless requests to the Steam API.

From my understanding the friend list requests cannot be batched like the other SteamAPI requests, so to start with we will probably just make 1 request for the user and not bother requesting everyone else's friends until we have a use for it.
