### ISSUE TITLE
Console output did not contain valid UTF-8

### ISSUE THREAD

**Issue by Conni243** [MegaAntiCheat/client-backend#8]
I've noticed this before but now have screenshots. Sometimes when im in a casual match this error appears in the console.
Is this intended?
![image](https://github.com/MegaAntiCheat/client-backend/assets/79007910/217893ec-c7e0-4b14-aa29-495c0f4a33e5)

**Comment by Bash-09** [comment]
Yes this is a known issue that will need to be resolved before release. I might make an issue for it so I don't forget.

**Comment by Bash-09** [comment]
Oh nvm this is an issue, lmao I'm dumb.

**Comment by lili7h** [comment]
Aiming to solve by rebuilding the logwatcher to use a self-managed UTF16 escaped buffer. Will reference the PR here when its ready.

**Comment by lili7h** [comment]
solved with #11.
