### ISSUE TITLE
Refuses to detect launch options

### ISSUE THREAD

**Issue by Seydix** [MegaAntiCheat/client-backend#84]
Triple checked to make sure all steps were followed correctly, and followed all suggestions found in bug report #45, but it still refuses to locate. I've done everything short of kludging the files, including what was recommended previously. The OS is windows 10 and it has never had any Apple software on it, below are logs of each attempt with the main methods along with the output.
  
![ex1Default](https://github.com/MegaAntiCheat/client-backend/assets/142464855/4d9c98dd-e8f7-4248-ad0e-dea68fd9a3d9)
![ex2ManualDir-i](https://github.com/MegaAntiCheat/client-backend/assets/142464855/4a6196bb-cdb4-4667-9a7f-aae20e1ef467)
![ex3ManualDir](https://github.com/MegaAntiCheat/client-backend/assets/142464855/32614b9d-273d-4f0e-9dd9-ce18c089236e)
![ex4AltPath](https://github.com/MegaAntiCheat/client-backend/assets/142464855/54e3a025-ac95-4f0e-b894-12aa8780ca82)
  
I'm genuinely hoping to get this running at some point, but help would be greatly appreciated. It should be noted that the directory was changed from default on C:, and I'll try any recommended fixes.

**Comment by megascatterbomb** [comment]
You've missed the second dash in the `--tf2-dir` launch option. In most cmdline executables, double dashes are required if the launch option is more than a single letter, and `cargo run` is no exception.

![image](https://github.com/MegaAntiCheat/client-backend/assets/55725012/40fe71d8-a8e4-4c7a-b402-c27d482b2b7c)

Hopefully using the correct syntax should work first try. Let us know if it doesn't.

**Comment by Seydix** [comment]
Will do, here's hoping.

**Comment by lili7h** [comment]
It seems to be failing to connect to RCon - I guess the first step would be to ensure TF2 is running, and the required rcon commands have been provided, and the RCon password is correct, then if thats all good and its still failing, we can dig into other potential issues

**Comment by Bash-09** [comment]
I recommend you try launch the game by itself, type the commands into the console yourself:
'''
ip 0.0.0.0
rcon_password mac_rcon
net start
'''
Then launching the app, and seeing if it connects then. If that still doesn't work. then we'll have to try figure something else out.

**Comment by Seydix** [comment]
Trying right now

**Comment by Bash-09** [comment]
Fixed in #115
