### ISSUE TITLE
Plans to support Linux ?

### ISSUE THREAD

**Issue by kabessao** [MegaAntiCheat/client-backend#9]
Sorry if this is the wrong place to post, but after reading your `faq` on your Discord server, I gathered that questions should be posted here.

My question is really simple: are there plans to support Linux ?

**Comment by lili7h** [comment]
This is OS independent. Bash builds, tests and runs in Linux, I build in windows. It already does and always will support linux. 😃

**Comment by kabessao** [comment]
oh, ok then :rofl: 
Thank you for the hard work
