### ISSUE TITLE
http://127.0.0.1:3621 shows up as a 404 error

### ISSUE THREAD

**Issue by Crash7890** [MegaAntiCheat/client-backend#95]
Everything was done correctly according to Megascatterbomb's tutorial, but when I pasted in the link "http://127.0.0.1:3621" like they do in the video, it shows up as a 404 error. 
![image](https://github.com/MegaAntiCheat/client-backend/assets/155827441/09e58f18-d251-4d13-a5da-b10834f51009)
I'm not sure why this is, but help would be appreciated.

**Comment by TehDrpStr** [comment]
try reinstalling. make sure that NOTHING interrupts the UI backend installation.

**Comment by FlamingLily** [comment]
> try reinstalling. make sure that NOTHING interrupts the UI backend installation.

This. Re-run ./include-ui.bat or .sh. I got the exact same thing, what happened is I closed the terminal window early because I thought it had finished. IIRC, the window closes itself when completed.

**Comment by Bash-09** [comment]
The cause for this tends to be that either the UI script was not run before build, or building the UI failed at some point.
I'm assuming this is resolved due to inactivity and not being directly an issue with the client.
